js-library/package-lock.json, js-library/package.json, js-library/src/request-verifiable-presentation.ts, js-library/src/tests/request-verifiable-presentation.spec.ts
Use uuid to define the request id instead of a sequencial number.
* Install `uuid` to create uuids.
* Create id with `uuid` library instead of variable `nextFlowIdCounter`.
Test coverage is the same but I had to change the implementation to get the id when the flow starts.
Using the callback strategy was not nice; therefore, I reimplemented the tests to use `async` and `await` and added a helper `startVcFlow` that returns the request id.
=> Use "nanoid" for request id

js-library/src/request-verifiable-presentation.ts, js-library/src/tests/request-verifiable-presentation.spec.ts
The main motivation is to allow the library to start multiple concurrent flows.
* Store opened windows in a Map instead of one single instance.
* Pass the flowId to the helper instead of creating it inside the helper.
* Scope the flowId per handler so that each handler is about one flow.
* Test that the function supports two concurrent flows.
=> Support concurrent flows

.github/workflows/publish.yml
Publish `@dfinty/verifiable-credentials` to NPM.
* Add the Github workflow that will publish to NPM new releases created in Github.
This is the same workflow used in ic-js, hardware-wallete-cli and generative-logo repository.
=> Workflow to publish a release

js-library/src/request-verifiable-presentation.ts, js-library/src/tests/request-verifiable-presentation.spec.ts
To validate the window post messages to avoid parsing messages that the code doesn't know what to do with them.
* Add validations in the handle function.
* Add comments to explain where the validation comes from.
* Added a test with "malicious" window messages from another origin and check that those don't affect the regular flow.
=> Add message validations

js-library/src/request-verifiable-presentation.ts, js-library/src/tests/request-verifiable-presentation.spec.ts
Improve how the library manages errors and exposes them to users.
The main improvement is to differentiate technical erros, which will output at onError, from not getting a credential for other reasons, which go to onSuccess with a different outout.
* Change onSuccess param type.
* Check whether user closes the window without finishing flow. We consider this as a technical error and ends up in `onError`.
* Changed `currentFlows` from a `Set` to a `Map` with the status of the current flow. Then the status is changed and checked during the flow.
* Remove skipped test `"calls onError with timeout error if flow doesn't start in five seconds"`. AuthClient doesn't manage it; therefore, I think that it makes sense we don't do it either.
* Implement test `"calls onError if user closes identity …
=> Manage Errors

js-library/package-lock.json, js-library/package.json, js-library/src/request-verifiable-presentation.ts, js-library/src/tests/request-verifiable-presentation.spec.ts
Improve the documentation and validation of the parameters expected by `requestVerifiablePresentation`.
* Wrap `new URL` with a try/catch to provide better feedback tot he user.
* Change types `string` for `Principal` for the credential subject and the issuer canister id.
* Add types for better documentation and developer experience.
* Add ts-doc comments and file comment.
* Test that onError is called when `identityProvider` is not a valid URL.
* Change params type in tests.
* Add `canisterId` to the expected request sent to IdentityProvider through window post message.
=> Improve parameters types and docs

CHANGELOG, js-library/README.md, js-library/package-lock.json, js-library/package.json
The library expects some parameters as `Principal` now. Therefore, it makes sense to add them as peerDependency so that users of the library also install them.
* Move `@dfinity/principal` to `peerDepedency`.
* Add the peer dependency installation in the readme.
No new functionality.
=> Add @dfinity/principal as peer dependency

CHANGELOG, js-library/src/request-verifiable-presentation.ts, js-library/src/tests/request-verifiable-presentation.spec.ts
Prepare the SDK for the improvements in developer experience discussed offline:
* `Issuer.canisterId` is mandatory.
* `derivationOrigin` should be avoided.
* Make `Issuer.canisterId` as mandatory.
* Make `derivationOrigin` optional.
Remove the `derivationOrigin: undefined` from the tests and add the canisterId in the shared issuer data.
=> Prepare for DX improvements

.gitignore, CHANGELOG, Cargo.lock, Cargo.toml, dfx.json, dummy-issuer/Cargo.toml, dummy-issuer/build.sh, dummy-issuer/dummy_issuer.did, dummy-issuer/src/lib.rs, dummy-issuer/tests/dummy_issuer.rs, dummy-relying-party/build.sh, dummy-relying-party/frontend/src/main.ts, dummy-relying-party/src/lib.rs
All teams developing a relying party will need an issuer to test their implementation.
In this PR, I introduce a canister that will issue any credential requested.
* New project "dummy_issuer" with canister implementing the Issuer API.
* Add dummy_issuer to dfx.json
* Add tests for the dummy issuer with Pocket IC.
=> Add Dummy Issuer

dfx.json, dummy-e2e/src/vc-flow.spec.ts, dummy-relying-party/frontend/index.html, dummy-relying-party/frontend/package-lock.json, dummy-relying-party/frontend/package.json, dummy-relying-party/frontend/postcss.config.js, dummy-relying-party/frontend/src/main.ts, dummy-relying-party/frontend/src/style.css, dummy-relying-party/frontend/tailwind.config.js, internet_identity.did
Main motivation is to deploy the dummy relying party to mainnet so that developers can get a grasp of the feature fast.
The idea is to link the RP in the dev docs for discoverability.
* Add mainnet network to dfx.json.
* Bumped the II version used.
* Install tailwind to dummy-relying-party and use it in index.html to build a nice UI.
* Change the dom manipulation of the JS file to be adapted to the new UI and offer a nice UX.
Relying party can be test here: https://l7rua-raaaa-aaaap-ahh6a-cai.icp0.io/
=> Add a nice UI for the dummy Relying Party

CHANGELOG, js-library/package.json
We discovered a bug in the JS library when the origins didn't match due to trailing slashes.
We fixed it by changing the type of the URL from `string` to `URL`.
I'd like to publish the fix before we publish the docs.
* Change package.json version to 0.0.2.
* Update CHANGELOG.
=> New Release of NPM package

.github/workflows/checks.yml, .github/workflows/rust.yml
Do not add breaking changes to dummy_issuer accidentally.
In this PR, I add the integration tests of the dummy_issuer to the CI.
* New workflow "Rust" to build the wasm and execute the tests.
Already running in the PR.
=> Add cargo test dummy_issuer to CI

dummy-relying-party/frontend/src/main.ts
The error message of requesting credentials was present after receiving a successful credential.
This is because the error container wasn't cleaned. This is why the mindset State -> UI is better than pure dom manipulation 😂 
* Clean up the error container when successfule credential is rendered.
Tested manually.
=> Dummy Relying Party: Remove error after successful credential

Cargo.lock, Cargo.toml, dummy-issuer/Cargo.toml, dummy-issuer/src/lib.rs, dummy-issuer/tests/dummy_issuer.rs
In preparation of moving `vc_util` to this repository, the dependencies need to be adjusted to be in line with what `vc_util` currently depends on.
In preparation of moving `vc_util` to this repository, the following
changes are made:
* remove direct dependency on iota fork
* non-validated JWT parsing is now done using `serde_json` directly
* move issuer dependencies to workspace Cargo.toml
* use consistent versions of `ic-cdk` and `ic-cdk-macros`
=> chore: Restructure rust dependencies and remove iota fork

.github/workflows/checks.yml, .github/workflows/nightly.yml, .github/workflows/publish.yml
Updates deprecated GitHub actions: checkoutv3 and setup-nodev3
=> Update outdated github actions

.github/workflows/playwright.yml, .github/workflows/rust.yml
This PR adds caching to the Cargo Test and Playwright workflows, which should improve its speed quite a bit.
Further changes should be made to CI to only build artifacts once. Currently each workflow builds their own. However, that will be done in separate PRs.
=> Add rust cache to CI

.github/workflows/release.yml
This PR sets up a workflow to publish a release when a tag with a `release-` prefix is pushed 
to the repository.
The created release will have the dummy issuer and dummy relying party attached as artifacts. These will later be referenced for `dfx deps` feature.
The release will only be created as a draft to allow for manual modifications before actually publishing.
=> Add GitHub actions workflow to create a release when pushing a release tag

.github/workflows/publish.yml, .gitignore, CHANGELOG.md, js-library/scripts/publish-npm.sh
Avod publishing `@dfinity/verifiable-credentials` if there were no changes in the library.
* New script `publish-npm.sh`.
* Use the new script in workflow publish.
* Add npm pack tarball extension to gitignore.
Tested manually.
=> Do not publish to npm if no changes

js-library/package-lock.json, js-library/package.json, js-library/scripts/update-version.mjs
Fetch API is supported in NodeJS since v18 and stable since v21. Given that the engine is set to v20 here and given what we are doing, as think it's probably fine to remove the `node-fetch` (we can run a "next" CI job to double check).
Update: Job worked out https://github.com/dfinity/verifiable-credentials-sdk/actions/runs/9869137332/job/27252340286
=> build: remove node-fetch

js-library/esbuild.mjs
In addition to test fiels, it's probably good to also skip mocks in the build.
=> build: ignore mocks

Cargo.lock, Cargo.toml, dummy-issuer/Cargo.toml, dummy-issuer/src/lib.rs, rust-packages/ic-verifiable-credentials/Cargo.toml, rust-packages/ic-verifiable-credentials/src/lib.rs
This PR removes the dependencies on the II and IC repositories. The only remaining non-published dependency is the the iota library fork, which I'm still working on and will be removed in a subsequent PR.
=> Switch to published IC libraries

js-library/package-lock.json, js-library/package.json
If we bump agent-js in ic-js in our dapps, we also need to bump it in the verifiable-credentials.
=> build: agent-js peer dependency v2

.github/workflows/rust.yml, rust-packages/ic-verifiable-credentials/src/lib.rs
The last PR (#49) unfortunately introduced a bug (confusion between DER encoded and raw canister signature public key). This PR fixes it.
In addition, #49 could only be merged, because the unit test for the rust library were not actually run. CI is changed to no run all rust tests.
=> Fix bug in canister sig public key handling

.github/workflows/publish.yml
Fix publish CI [issue](https://github.com/dfinity/verifiable-credentials-sdk/actions/runs/10789761112/job/29923443711)
- The script `publish-npm.sh` find place in a parent folder now that we release from `dist`, so `../` instead of `./`
=> fix: ci publish not finding script

Cargo.lock, Cargo.toml, dummy-issuer/Cargo.toml, rust-packages/ic-verifiable-credentials/Cargo.toml, rust-packages/ic-verifiable-credentials/src/lib.rs
This PR replaces the forked version of the iota identity.rs libraries with the original ones (including the up-streamed changes).
=> chore: Replace identity.rs fork with upstream

Cargo.lock, rust-packages/ic-verifiable-credentials/Cargo.toml, rust-packages/ic-verifiable-credentials/src/lib.rs
II uses the old domain `ic0.app` to derive the principals even when the dapp is hosted in the new domain `icp0.io`. This happens in the `remapToLegacyDomain` helper in II.
Therefore, the origin of the id alias credential uses the old domain `ic0.app` even though the dapp is hosted in the new domain `icp0.io`.
Instead of requiring the developers to understand and know about this implementation detail, we decided to map the new domain of the expected origin to the old domain before comparing them.
* New helper `remap_to_legacy_domain`.
* Use new helper when comparing domains.
* Add tests for the helper.
* Add a test where the expected origin uses the new domain.
=> Remap new domain to old domain in expected origin for id alias

CHANGELOG.md, Cargo.lock, Cargo.toml, js-library/package-lock.json, js-library/package.json, rust-packages/ic-verifiable-credentials/Cargo.toml
Release `ic-verifiable-credentials` to crates.io with v1.0.0 and bump the js-library to keep it consistent.
* Bump to v1.0.0 in Cargo.toml and package.json files.
* Changelog
* Changes in Cargo.lock.
* Changes in package-lock.json in the js-library.
Not necessary.
=> Prepare release v1.0.0

rust-packages/ic-verifiable-credentials/Cargo.toml
Publishing to crates.io failed because of missing license.
* Add `license` entry in the package Cargo.toml
* I tried the publishing command with `--dry-run` and all tests passed.
=> Add license entry in package Cargo.toml

.github/workflows/publish-crate.yml
We want to publish `ic-verifiable-credentials` to crates.io.
* Add a workflow to publish manually or when a new release is created.
I hope to test it when the secret is added. I will then create a new release and the workflow will be triggered.
If it works, I will then do a PR to remove the manual trigger option. Otherwise, I will do a branch to try to fix it and trigger it manually.
=> Add workflow to publish to crates.io

Cargo.lock, README.md, rust-packages/ic-verifiable-credentials/Cargo.toml, rust-packages/ic-verifiable-credentials/README.md
The library is published in crates.io but there is no readme for developers to understand what this library is about.
* Edit main README to introduce the new library.
* Add new README for `ic-verifiable-credentials` which will be fetched by crates.io.
Only doc changes.
=> Add readme for `ic-verifiable-credentials` and bump library

.github/workflows/publish-crate.yml
Crates must be published from a personal account instead of with a CI (for now).
* Disable the `publish-crate` workflow.
Not tested because there is nothing to run.
=> Disable publish-crate workflow

js-library/package-lock.json, js-library/package.json
CI `checks` are failing - e.g. https://github.com/dfinity/verifiable-credentials-sdk/actions/runs/16936244767/job/47993367472?pr=87. It looks like vite now explicitely requires jsdom to be specified. Weird as it seems we did not upgrade vitest recently. Nevertheless, this PR is meant to unlock the CI.
It seems that pinning Node LTS also resolves it - see https://github.com/dfinity/verifiable-credentials-sdk/pull/89 - but still, given that vitest anyway requires jsdom, not too bad to list it anyway.
-`npm i jsdom -D`
=> build: add jsdom as dev dependency
